### PR TITLE
added feature -php_compat

### PR DESCRIPTION
**Pull request by Sadrak**
* new feature php_compat
 * rudimentary support for PHP parse_ini_file() syntax
  * one configfile for Perl and PHP scripts is with -php_compat now possible
  * rename _casify to _assimilate (bad naming)

### CODE REVIEW

**Comment by Sadrak** [comment]
see https://rt.cpan.org/Public/Bug/Display.html?id=102339

I am absolute unhappy with the renaming of _casify to _assimilate ... sorry for that, perhaps you have a way better name.

**Comment by shlomif** [comment]
Can you:

1. Keep the name of ->_caseify to make the patch less intrusive.

2. Fix the appveyor and travis builds?

Thanks!

**Comment by Sadrak** [comment]
I never used appveyor before and i can't see an errormessage. Only a wrong exitcode and a failure that has nothing todo with my changes. Can you guide me through appveyor?

**Comment by shlomif** [comment]
@Sadrak : let's try some rebuilds.

**Comment by shlomif** [comment]
Thanks!

**Pull request merged**
